server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zoezn/Final-BackendII
          default-label: main
          force-pull: true
          search-paths: configData



