# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-post
          uri: lb://ms-post
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
      default-filters:
        - TokenRelay
        #- RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          digital-house:
            client-id: digital-house-spring-gateway-client
            client-secret: txkhKnPGKvfX2mBbyDSve0sSFWD9PAgT
            scope: openid, email, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/digital-house
        provider:
          digital-house:
            issuer-uri: http://localhost:8080/realms/digital-house
            jwk-set-uri: http://localhost:8080/realms/digital-house/protocol/openid-connect/certs
